# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exec_instances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementParseRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_member_name', models.CharField(max_length=200)),
                ('element_member_position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=5)),
                ('element_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('val', models.CharField(max_length=24)),
                ('atom_type', models.CharField(max_length=5)),
                ('aeps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exec_instances.AEPS')),
            ],
        ),
        migrations.CreateModel(
            name='SiteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atom_member_name', models.CharField(max_length=200)),
                ('atom_member_value', models.CharField(max_length=96)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exec_instances.Site')),
            ],
        ),
        migrations.RemoveField(
            model_name='execinstance',
            name='date_time',
        ),
        migrations.AddField(
            model_name='registeredelement',
            name='exec_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exec_instances.ExecInstance'),
        ),
        migrations.AddField(
            model_name='elementparserule',
            name='registered_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exec_instances.RegisteredElement'),
        ),
    ]
