# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exec_instances', '0002_auto_20170716_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='execinstance',
            name='grid_size',
            field=models.IntegerField(default=0),
        ),
    ]
