# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exec_instances', '0003_execinstance_grid_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('actual_aeps', models.CharField(max_length=50)),
                ('aeps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exec_instances.AEPS')),
            ],
        ),
    ]
